name: Run Test, Build and Push to DockerHub

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install depend
        run: docker compose -f docker-compose.yml run --rm app make setup
            
      - name: Run tests
        run: docker compose -f docker-compose.yml up --abort-on-container-exit
      
      - name: Build product images
        run: docker compose -f docker-compose.yml build app

      - name: Push to DockerHub
        run: docker compose -f docker-compose.yml push app
